import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { motion } from 'framer-motion'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Framer-Motion Basics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div>
        <motion.h1 className={styles.title}
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{delay: .8, duration: 1.5}}
        whileHover={{scale: 1.1, transition: {yoyo: Infinity}}}
        >
          Framer-Motion Basics
        </motion.h1>

        <p className={styles.description}>
          Testing the Framer-Motion Library
        </p>
        </div>
        
      </main>
    </div>
  )
}
